### ISSUE TITLE
Support for Drupal 8

### ISSUE THREAD

**Issue by dolfim** [drupalauth/simplesamlphp-module-drupalauth#32]
Is support for Drupal 8 planned?

**Comment by marqpdx** [comment]
I'd be very interested in this as well. 

if anyone has code started, i'd be glad to test and/or add code.

thanks,

m

**Comment by Dopeyr** [comment]
There has been some code done in this fork https://github.com/piersharding/drupalauth

**Comment by RoSk0** [comment]
Added in 1.8.0-alpha1.
