### ISSUE TITLE
Reimplement this module properly

### ISSUE THREAD

**Issue by jaimeperez** [drupalauth/simplesamlphp-module-drupalauth#35]
Hi,

This module does not really follow the SimpleSAMLphp guidelines on creating authentication sources, creating trouble for users who are configuring SimpleSAMLphp to use the PHP session handler.

While it is true that the code itself and the documentation mention this incompatibility, most users don't read it and have all sorts of problems that are too difficult for them to debug. This leads to frustrated users coming to our mailing list, asking for support to fix something that's not SimpleSAMLphp's fault. The worst part here is that there's really no reason for this limitation nowadays.

Here are the problems that I have identified from a first glance at the `drupalauth:External` class:

* Drupal's bootstrapping is done with `DRUPAL_BOOTSTRAP_FULL`, which is probably not necessary, and has lots of side effects like overriding SimpleSAMLphp's error handler and making it extremely difficult to handle error conditions.

* The `__construct()` method should be limited to setting up the auth source basics, and everything needed to perform authentication should be done in the `authenticate()` method. In particular, Drupal's environment should not be initialized in the constructor. While the footprint of code between the call to the constructor and the call to `authenticate()` is currently very small, this could change in the future. Given that the Drupal environment is being loaded before the call to `authenticate()`, it could break SimpleSAMLphp's environment and cause problems if anything else than state initialization is ever done in between.

* **Before** initializing Drupal (and its session), SimpleSAMLphp's session should be closed to avoid the former interfere with the latter. In this case, however, the `SimpleSAML_Session::cleanup()` method cannot be used, since in this flow there won't be a _previous session_ (the request is handled by SimpleSAMLphp from the beginning). This means the code at the beginning of `authenticate()` should fetch SimpleSAMLphp's session handler, check if it's the PHP session handler, and in that case close the session to ensure no information is lost before handing control over to Drupal:

```php
private function initDrupal() {
        $a = getcwd();
        chdir(DRUPAL_ROOT);
        require_once(DRUPAL_ROOT.'/includes/bootstrap.inc');
        require_once(DRUPAL_ROOT.'/includes/file.inc');

        // bootstrap Drupal's session
        drupal_bootstrap(DRUPAL_BOOTSTRAP_SESSION);

        drupal_load('module', 'system');
        drupal_load('module', 'user');
        drupal_load('module', 'field');
        chdir($a);
}

public function authenticate(&$state) {
    assert('is_array($state)');

    $session = SimpleSAML_Session::getSessionFromRequest();

    $sh = SimpleSAML_SessionHandler::getSessionHandler();
    if ($sh instanceof SimpleSAML_SessionHandlerPHP) {
        // SimpleSAMLphp is using PHP sessions, close the session before we go on
        $sh->saveSession($session);
        session_write_close();
    }

    $this->initDrupal();

    $attributes = $this->getUser();

    // we are done, restore SimpleSAMLphp's session
    SimpleSAML_Session::getSessionFromRequest();

    // check if we are already authenticated
    if ($attributes !== NULL) {
        $state['Attributes'] = $attributes;
        return;
    }

    // redirect to Drupal's login page
     ...
}
```

I haven't looked much at the `drupalauth:UserPass` authentication source, but I see more or less the same applies to it.

**Comment by RoSk0** [comment]
Hi @jaimeperez ,

I have tried to implement what you described but it's still doesn't work as expected. When testing auth source you are not redirected to the "Your attributes" page if SimpleSAMLphp uses phpsession. So something is lost and I just can't figure out is it lost from session or state. Any ideas?

**Comment by jaimeperez** [comment]
Hi @RoSk0!

SimpleSAMLphp stores the state in the session itself, so if the session is lost, so is the state. Similarly, if you get an error saying the state is lost, that's 99.9% of the time due to the session being lost.

If you are not redirected to the page displaying your attributes, what happens instead?

**Comment by RoSk0** [comment]
I saw the same login form when testing. I had multiple auth sources configured and multisource was chosen then I saw its select auth source page.

**Comment by jaimeperez** [comment]
Have you tried with a simple authentication source?

Also, have you tried monitoring the HTTP exchange with something like the SAMLtracer plugin for firefox or chrome? What do the SSP logs say?

**Comment by RoSk0** [comment]
Closing outdated.
