### ISSUE TITLE
Accept query parameters in drupal_login_url config

### ISSUE THREAD

**Issue by joaopauloctga** [drupalauth/simplesamlphp-module-drupalauth#37]
Hello,
In my current project we need to set the url with query string parameter, but the actual results is wrong because this module concatenate value defined in `drupal_login_url` with `"?ReturnTo=".$returnTo`, so he generated a url with two chars "?" and broken the url.

We change this concatenation for check if has parameters in `drupal_login_url` url, if has we concatenate and generated correct URL.

**Comment by RoSk0** [comment]
Closing outdated.
