### ISSUE TITLE
Atttibutes + field values from profiles

### ISSUE THREAD

**Issue by cb29** [drupalauth/simplesamlphp-module-drupalauth#54]
Hello,

how can I pass field values from profiles in the attributes array?

Thanks.

**Comment by RoSk0** [comment]
It depends on what do you mean by profiles, if you refer to something like user fields stored in a node then you will need to implement [Authentication Processing Filters in SimpleSAMLphp](https://simplesamlphp.org/docs/stable/simplesamlphp-authproc) .

**Comment by RoSk0** [comment]
Closing outdated.
