### ISSUE TITLE
Database error on multisite installation

### ISSUE THREAD

**Issue by cb29** [drupalauth/simplesamlphp-module-drupalauth#55]
Hello,
When visiting the authsource on the simplesaml server (authentication sources > custom source) It seems that we get an error on a multisite installation :
`Drupal\Core\Database\ConnectionNotDefinedException: The specified database connection is not defined: default`

No problem, if the settings.php is located in sites/default directory.

Do you have seen this problem?

Thanks.

**Comment by cato-cit** [comment]
It's similar to #58 and seems be fix in #59

**Comment by RoSk0** [comment]
Closed by #59
