### ISSUE TITLE
Roles don't get added to the attributes array.

### ISSUE THREAD

**Issue by kcolwell** [drupalauth/simplesamlphp-module-drupalauth#56]
When using Drupal 8 as an IDP for a Drupal 7 site I couldn't get roles to appear when setting the attributes to the following:

       array('field_name' => 'roles', 'attribute_name' => 'roles'),

However when removing the attributes array from the authsources.php file so that all attributes are shown the roles do appear. However the key for the array is roles:0:target_id. Instead of uid:0:value. I couldn't figure out where that difference appears in the code.

When setting the user info and syncing for a Drupal 7 site while not listing the individual attributes in the authsources.php file the array names include :0:value. Using the longer array keys for some fields works nicely. (Like uid:0:value or name:0:value) However this doesn't work for the roles field which does additional processing based on colons. 

To get the non-attributes to work I edited the getAllAttributes function within DrupalHelper.php to remove the extra long array keys.

` 

    protected function getAllAttributes($drupaluser, $forbiddenAttributes)
    {
        $attributes = [];
        foreach ($drupaluser as $field_name => $field) {
            if (!in_array($field_name, $forbiddenAttributes, true)) {
                $count = $field->count();

                $field_properties = $field
                    ->getFieldDefinition()
                    ->getFieldStorageDefinition()
                    ->getPropertyDefinitions();
                foreach ($field_properties as $property_name => $property_definition) {
                    if (!$property_definition->isComputed() && !$property_definition->isInternal()) {
                        $index = 0;
                        while ($index < $count) {
                            $property_value = $field->get($index)->{$property_name};
                            if (!empty($property_value) && is_scalar($property_value)) {
                                $attributes["$field_name:$index:$property_name"][] = $property_value;
                            }
                            $index++;
                        }
                    }
                }
            }
        }
        // Removes :0:value or :0:target_id from the array keys that look like this: uid:0:value
        // Since the roles are later parsed by simplesamlphp based on a colon this must be removed.
        foreach ($attributes as $k => $v) {
          // Check to make sure that the value does include the colon.
          if (strpos($k, ':') !== false) {
            // Uses explode function to divide the key into an array based on the colon.
            $new_key = explode(":", $k);
            // If there are not multiple attributes for the same key.
            if (!$attributes[$new_key[0]]){
              // Takes the value of the original key and adds it to the array with a new key name with the first string from the explode function.
              $attributes[$new_key[0]] = $v;
            }
            else {
              // If there are multiple attributes for the same key add the secondary value to the array.
              array_push($attributes[$new_key[0]], $v[0]);
            }
            // Removes the original key and value.
            unset($attributes[$k]);
          }
        }
        return $attributes;
    }
`

**Comment by RoSk0** [comment]
Because roles are actually reference field you need to specify `field_property` to get something out. I update example config make it obvious. Take a look here https://github.com/drupalauth/simplesamlphp-module-drupalauth/commit/cc8cd6feb32708ad8b51b66eb3b7e16334095b22
