### ISSUE TITLE
Failure to return from simplesaml back to SP when already logged in

### ISSUE THREAD

**Issue by stesi561** [drupalauth/simplesamlphp-module-drupalauth#70]
I've got the following set up:

IDP: Drupal 9
Simplesamlphp
This module 1.8.0-beta2  + patch to get working on D9 (https://github.com/drupalauth/simplesamlphp-module-drupalauth/pull/61)
Login using Drupal login

Wordpress + https://wordpress.org/plugins/wp-saml-auth/

I've previously got the above working with D8.8.

In this case I'm seeing the following behaviour when not already logged in.

On login form Wordpress I get taking through to simplesamlphp and then to Drupal login page. Once there everything appears to run through to completion - however I don't get returned back to wordpress and the browser halts on a white page at the following url:

simplesaml/module.php/drupalauth/resume.php?State=_[REMOVED]%3A[BASEURL]simplesaml/saml2/idp/SSOService.php%3Fspentityid%3Durn%253Aalpineclub-wp.fudev.co.nz%26RelayState%3D%252Fwp-login.php%253Faction%253Dwp-saml-auth%26cookieTime%3D1610399519

Refreshing this page returns me back to wordpress.

Debug level Logging enabled in SimpleSamlPHP config.
I don't see any errors in syslog, php fpm error log, Drupal watchdog.
The browser reports a status of 200. 

Note: If I am already logged in in drupal I am returned successfully back to wordpress.

I assume this is a fatal D9 error that is being caught in Drupal and somehow not finding it's way into watchdog logs.

**Comment by stesi561** [comment]
Testing on master - shows error on screen of:
SAML2\HTTPPost::__set_state(array( 'destination' => NULL, ))

**Comment by stesi561** [comment]
Okay - by using restore_exception_handler I was able to track this down to
 SimpleSAML\Error\Exception: Error 1 - Undefined class constant 'UPPER' at /vendor/symfony/http-foundation/ResponseHeaderBag.php:115

Drupal 9 also includes this dependency and it looks like this version is being loaded in preference to the simplesaml version - the simplesaml install I was using had version 3.x for symfony/* requirements however allowed for use of 4.x

I updated composer.json to require a similar version as Drupal (~4.4) for all of the symphony/* requirements that were shared and this resolved the issue.

As this is not something that can be done by a pull request here I think the most appropriate step is to include this in documentation?

**Comment by RoSk0** [comment]
Thanks for the investigation and report .

It's good that you got to the bottom of the issue but unfortunately I believe that this was problem with your particular set up. Drupal requires `"symfony/*": "^4.4",` since 9.0.0-alpha1 so there should be no situation when Symfony v3 components are used with Drupal 9.
