### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by azovsky** [drupalauth/simplesamlphp-module-drupalauth#78]
**Issue**
Trying to install `simplesamlphp-module-drupalauth 1.8.1` via composer on PHP 8.x.
Errors:
```
Problem 1
    - drupalauth/simplesamlphp-module-drupalauth is locked to version 1.8.1 and an update of this package was not requested.
    - drupalauth/simplesamlphp-module-drupalauth 1.8.1 requires php ^5.6.0|^7.0 -> your php version (8.0.10) does not satisfy that requirement.
  Problem 2
    - simplesamlphp/simplesamlphp is locked to version v1.19.1 and an update of this package was not requested.
    - simplesamlphp/simplesamlphp v1.19.1 requires php >=7.1 <8.0 -> your php version (8.0.10) does not satisfy that requirement.
  Problem 3
    - drupalauth/simplesamlphp-module-drupalauth 1.8.1 requires php ^5.6.0|^7.0 -> your php version (8.0.10) does not satisfy that requirement.
    - drupal/drupalauth4ssp 1.2.0 requires drupalauth/simplesamlphp-module-drupalauth ~1.8.0 -> satisfiable by drupalauth/simplesamlphp-module-drupalauth[1.8.1].
    - drupal/drupalauth4ssp is locked to version 1.2.0 and an update of this package was not requested.
```

**To Reproduce**
On Ubuntu with PHP 8.0.10, 
Add in `composer.json` : in `require` `"drupalauth/simplesamlphp-module-drupalauth": "^1.8"`
Run `composer isntall`

**Information:**

- PHP version in use 8.0.10
- Drupal core version 9.2.4 
- Ubuntu 20.04.2 LTS /

**Comment by Azovsky** [comment]
I deleted `composer.lock` and run `composer install`. It looks like the old version has been installed `simplesamlphp-module-drupalauth =1.8.0-beta2` - it doesn't require PHP 5/7 version limited.
Installation is working now. Will check the rest.
Thanks!
