### ISSUE TITLE
Crypt::hashEquals

### ISSUE THREAD

**Issue by benlamptey** [drupalauth/simplesamlphp-module-drupalauth#83]
```
                if (!Crypt::hashEquals($hash, $cookie_hash)) {
                    throw new Exception(
                        'Cookie hash invalid. This indicates either tampering or an out of date drupal4ssp module.'
                    );
                }
```
`hashEquals` no longer exists in Drupal 9, and it has been suggested to use PHP's built-in function `hash_equals`
https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Utility%21Crypt.php/function/Crypt%3A%3AhashEquals/8.9.x

**Comment by benlamptey-gocity** [comment]
ignore - i can actually see this has been updated 2 years ago...must have been referencing an old version
