### ISSUE TITLE
Module seems to work except I get odd behavior with the test authentication sources link

### ISSUE THREAD

**Issue by frob** [drupalauth/simplesamlphp-module-drupalauth#85]
**Not sure yet if this is a bug report or a support requets**
I have simplesamlphp installed via composer. The project seems to be working. I installed using this guide https://dev.to/esnare/single-sign-on-with-simplesamlphp-and-drupal-9-1h1b with one exception. I am installing native and not using lando or docker.

Everything looks like it is working until I get to the "Testing your work so far" section. If I click on `drupal-userpass` to test my authentication sources. 

![image](https://user-images.githubusercontent.com/316176/211089028-94a3273a-e825-42e1-a86e-3ee58802a9c8.png)

If not logged in already I get an error that the page is a 404 error page. If I am logged in then I get a breakdown of metadata for my user.

According to the guide I am supposed to get redirected to the login page of drupal when I click on that link.

In my logs I see:

```
AH01797: client denied by server configuration: /var/www/example/current/web/public/core/example.net, referer: https://example.net/simplesaml/module.php/core/authenticate.php?as=drupal-userpass
```

- PHP version in use 
  - 7.4
- Drupal core version
  - 9.5
- SimpleSAMLphp version
  - 1.19
- webserver version and configuration
  - Apache
  
  ```
  # SimpleSAMLphp settings
        SetEnv SIMPLESAMLPHP_CONFIG_DIR /var/www/example.net/current/config/simplesamlphp
        Alias /simplesaml /var/www/example.net/current/vendor/simplesamlphp/simplesamlphp/www
        <Directory /var/www/example.net/current/vendor/simplesamlphp/simplesamlphp/www>
                Require all granted
        </Directory>
```

**Additional context**

**Comment by RoSk0** [comment]
You clearly have a typo in your configuration:
- Apache error shows `/var/www/example/current/web/public/core/example.net` file system path
- SimpleSAMLphp Apache configuration shows `/var/www/example.net/current/config/simplesamlphp`
