### ISSUE TITLE
Drupal 10?

### ISSUE THREAD

**Issue by hyperlogos** [drupalauth/simplesamlphp-module-drupalauth#87]
Just checking to see if there are any plans to make this module work with D10+, modern simplesamlphp, etc., or if it's run its course. I'm not getting miniorange_saml_idp to work (although I think the problem is actually in miniorange_saml) so this is currently my only hope of getting Drupal to behave as literally any kind of IdP to drupal SPs. There is a patch that appears to make drupalauth4ssp work with D10.

**Comment by RoSk0** [comment]
Plans are there, but no exact time frames at this stage.

Patches welcome as usual

**Comment by RoSk0** [comment]
Fixed and released in the [version 2.10.0-rc.1](https://github.com/drupalauth/simplesamlphp-module-drupalauth/releases/tag/2.10.0-rc.1). 

Please test and report any issues.
