### ISSUE TITLE
Deprecated Drupal\Component\Utility\Crypt::hashEquals

### ISSUE THREAD

**Issue by khaldoonmasudalliance** [drupalauth/simplesamlphp-module-drupalauth#88]
Getting PHP error on Drupal 9.5.7:
Error: Call to undefined method Drupal\Component\Utility\Crypt::hashEquals() in SimpleSAML\Module\drupalauth\Auth\Source\External->getUser() (line 139 of /app/vendor/simplesamlphp/simplesamlphp/modules/drupalauth/lib/Auth/Source/External.php)

It needs to be replaced by php hash_equals as per https://www.drupal.org/node/3054488

**Comment by RoSk0** [comment]
Closing outdated.
