### ISSUE TITLE
SimpleSAML 2.x support

### ISSUE THREAD

**Issue by stesi561** [drupalauth/simplesamlphp-module-drupalauth#89]
SimpleSAMLPHP is indicating -> The 1.19 branch will receive security and critical bug fixes until the end of 2023.
https://github.com/simplesamlphp/simplesamlphp/security

Is there any plans afoot for a 2.9 or 2.10 release for this module before then?

**Comment by RoSk0** [comment]
Fixed and released in the https://github.com/drupalauth/simplesamlphp-module-drupalauth/releases/tag/2.10.0-rc.1 . 

Please test and report any issues.
